package com.dangelo.xxoa.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FILE_INFO".
 */
public class FileInfo {

    private Long id;
    private String FileUrl;
    private String FileName;
    private String Filepath;
    private String Filetype;

    public FileInfo() {
    }

    public FileInfo(Long id) {
        this.id = id;
    }

    public FileInfo(Long id, String FileUrl, String FileName, String Filepath, String Filetype) {
        this.id = id;
        this.FileUrl = FileUrl;
        this.FileName = FileName;
        this.Filepath = Filepath;
        this.Filetype = Filetype;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileUrl() {
        return FileUrl;
    }

    public void setFileUrl(String FileUrl) {
        this.FileUrl = FileUrl;
    }

    public String getFileName() {
        return FileName;
    }

    public void setFileName(String FileName) {
        this.FileName = FileName;
    }

    public String getFilepath() {
        return Filepath;
    }

    public void setFilepath(String Filepath) {
        this.Filepath = Filepath;
    }

    public String getFiletype() {
        return Filetype;
    }

    public void setFiletype(String Filetype) {
        this.Filetype = Filetype;
    }

}
