package com.dangelo.xxoa.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYS_MSG".
 */
public class SysMsg implements java.io.Serializable {

    private Long id;
    private java.util.Date date;
    private String mynumber;
    private String title;
    private String content;
    private String isread;
    private String arg1;
    private String arg2;

    public SysMsg() {
    }

    public SysMsg(Long id) {
        this.id = id;
    }

    public SysMsg(Long id, java.util.Date date, String mynumber, String title, String content, String isread, String arg1, String arg2) {
        this.id = id;
        this.date = date;
        this.mynumber = mynumber;
        this.title = title;
        this.content = content;
        this.isread = isread;
        this.arg1 = arg1;
        this.arg2 = arg2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getMynumber() {
        return mynumber;
    }

    public void setMynumber(String mynumber) {
        this.mynumber = mynumber;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getIsread() {
        return isread;
    }

    public void setIsread(String isread) {
        this.isread = isread;
    }

    public String getArg1() {
        return arg1;
    }

    public void setArg1(String arg1) {
        this.arg1 = arg1;
    }

    public String getArg2() {
        return arg2;
    }

    public void setArg2(String arg2) {
        this.arg2 = arg2;
    }

}
